#pragma once
// Host dims-drift suite for the code-authored overlay/effect sheets (bead
// monhun-ardu-42n.2). src/generated/art_dims.hpp is emitted by tools/gen-art.py
// from tools/fxdump.cpp, which reads the same src/core/game.hpp tables the sim
// uses: these tests re-derive every hw/hh/reach from the core accessors, so a
// tuning change in game.hpp fails make test until `make gen` regenerates the
// header AND the sheets.
//
// The sheet presence tests parse fxdata/blocks/Sprites.txt (generated by
// tools/convert-sprite.py from the PNGs) and check that each declared hit box
// really has painted (mask=1) pixels at the exact frame rect the blobs claim.
// That is the host end of the pixel-exactness chain: core dims -> fxdump JSON
// -> gen-art.py PNG -> convert-sprite blob.
#include "test.hpp"
#include "../src/core/game.hpp"
#include "../src/generated/art_dims.hpp"

#include <stdio.h>
#include <string>

using namespace mh;

namespace artdimstest {

const char *const BLOCK_SHEETS = "fxdata/blocks/Sprites.txt";

// ------------------------------------------------------------ blob parsing

// Find `uint8_t <sym>[] = {` and decode the decimal bytes up to `};`.
bool readBlob(const std::string &sym, std::vector<int> &out, std::string &err) {
    FILE *f = fopen(BLOCK_SHEETS, "rb");
    if (f == nullptr) {
        err = std::string("cannot open ") + BLOCK_SHEETS;
        return false;
    }
    std::string text;
    char buf[4096];
    size_t n;
    while ((n = fread(buf, 1, sizeof(buf), f)) > 0)
        text.append(buf, n);
    fclose(f);

    const std::string decl = "uint8_t " + sym + "[] =";
    const size_t at = text.find(decl);
    if (at == std::string::npos) {
        err = sym + ": declaration not found";
        return false;
    }
    const size_t open = text.find('{', at);
    const size_t close = text.find('}', open);
    if (open == std::string::npos || close == std::string::npos) {
        err = sym + ": malformed declaration";
        return false;
    }
    out.clear();
    size_t i = open + 1;
    while (i < close) {
        while (i < close && (text[i] == ' ' || text[i] == '\n' || text[i] == '\r' || text[i] == '\t' || text[i] == ','))
            i++;
        if (i >= close)
            break;
        int v = 0;
        while (i < close && text[i] >= '0' && text[i] <= '9') {
            v = v * 10 + (text[i] - '0');
            i++;
        }
        out.push_back(v);
    }
    return true;
}

// A plus-mask sheet blob: 2-byte w/h header then per frame, per shade pass,
// per 8-px page, per column a (data, mask) pair.
struct Blob {
    int w = 0, h = 0, frames = 0;
    std::vector<int> bytes;
};

bool parseBlob(const char *sym, Blob &out, Test &t) {
    std::vector<int> raw;
    std::string err;
    if (!readBlob(sym, raw, err) || raw.size() < 2) {
        t.assert(1, 0, err.empty() ? std::string(sym) + ": empty blob" : err);
        return false;
    }
    out.w = raw[0];
    out.h = raw[1];
    out.bytes.assign(raw.begin() + 2, raw.end());
    const int frame_bytes = ((out.h + 7) / 8) * out.w * 3 * 2;
    out.frames = frame_bytes > 0 ? static_cast<int>(out.bytes.size()) / frame_bytes : 0;
    return true;
}

// bit of a page byte: pixel y has bit y&7; normalized to 1/0 so the suite's
// assert() can compare directly.
inline int bitAt(int y, int value) {
    return (value >> (y & 7)) & 1;
}

// convert-sprite.py layout: per frame, 3 shade passes; each pass is
// page_count * w (data, mask) pairs in column-then-page order. The stored
// masks are the per-plane AND complements (mask=1 with data=0 is an eraser).
int pixelData(const Blob &b, int frame, int shade, int x, int page) {
    const int page_count = (b.h + 7) / 8;
    return b.bytes[((frame * 3 + shade) * page_count + page) * b.w * 2 + x * 2];
}
int pixelMask(const Blob &b, int frame, int shade, int x, int page) {
    const int page_count = (b.h + 7) / 8;
    return b.bytes[((frame * 3 + shade) * page_count + page) * b.w * 2 + x * 2 + 1];
}

// ------------------------------------------------------- small helpers

int16_t coreHw(const Attack *a) {
    return attackHw(a);
}
int16_t coreHh(const Attack *a) {
    return attackHh(a);
}
int16_t coreReach(const Attack *a) {
    return attackReach(a);
}
int16_t monHw(const MonsterAttack *a) {
    return monsterAttackHw(a);
}
int16_t monHh(const MonsterAttack *a) {
    return monsterAttackHh(a);
}

// ----------------------------------------------------------- dims vs core

// Branch attacks are drawn through the same overlay path as the main attacks
// (sword step-slash / spin-cut in particular), so their boxes must be dumped
// and pinned too.
void assertBranchDims(Test &t, const WeaponDef *w, const char *what) {
    t.assert(art_dims::sword_branch0_hw, coreHw(branchAtk(weaponBranch(w, 0))), "sword branch0 hw");
    t.assert(art_dims::sword_branch0_hh, coreHh(branchAtk(weaponBranch(w, 0))), "sword branch0 hh");
    t.assert(art_dims::sword_branch0_reach, coreReach(branchAtk(weaponBranch(w, 0))), "sword branch0 reach");
    t.assert(art_dims::sword_branch1_hw, coreHw(branchAtk(weaponBranch(w, 1))), "sword branch1 hw");
    t.assert(art_dims::sword_branch1_hh, coreHh(branchAtk(weaponBranch(w, 1))), "sword branch1 hh");
    t.assert(art_dims::sword_branch1_reach, coreReach(branchAtk(weaponBranch(w, 1))), "sword branch1 reach");
    (void)what;
}

void testCoreDimMirrors(Test &t) {
    std::cout << "---------- art dims match core accessors ----------" << std::endl;
    const WeaponDef *w = &WEAPON_DEFS[0];
    t.assert(art_dims::sword_atk0_hw, coreHw(weaponAttack(w, 0)), "sword atk0 hw");
    t.assert(art_dims::sword_atk0_hh, coreHh(weaponAttack(w, 0)), "sword atk0 hh");
    t.assert(art_dims::sword_atk0_reach, coreReach(weaponAttack(w, 0)), "sword atk0 reach");
    t.assert(art_dims::sword_atk1_hw, coreHw(weaponAttack(w, 1)), "sword atk1 hw");
    t.assert(art_dims::sword_atk1_hh, coreHh(weaponAttack(w, 1)), "sword atk1 hh");
    t.assert(art_dims::sword_atk1_reach, coreReach(weaponAttack(w, 1)), "sword atk1 reach");
    t.assert(art_dims::sword_atk2_hw, coreHw(weaponAttack(w, 2)), "sword atk2 hw");
    t.assert(art_dims::sword_atk2_hh, coreHh(weaponAttack(w, 2)), "sword atk2 hh");
    t.assert(art_dims::sword_atk2_reach, coreReach(weaponAttack(w, 2)), "sword atk2 reach");
    t.assert(art_dims::sword_special_hw, coreHw(weaponSpecial(w)), "sword special hw");
    t.assert(art_dims::sword_special_hh, coreHh(weaponSpecial(w)), "sword special hh");
    t.assert(art_dims::sword_special_reach, coreReach(weaponSpecial(w)), "sword special reach");
    assertBranchDims(t, w, "sword");

    w = &WEAPON_DEFS[1];
    t.assert(art_dims::flail_atk0_hw, coreHw(weaponAttack(w, 0)), "flail atk0 hw");
    t.assert(art_dims::flail_atk0_hh, coreHh(weaponAttack(w, 0)), "flail atk0 hh");
    t.assert(art_dims::flail_atk0_reach, coreReach(weaponAttack(w, 0)), "flail atk0 reach");
    t.assert(art_dims::flail_atk1_hw, coreHw(weaponAttack(w, 1)), "flail atk1 hw");
    t.assert(art_dims::flail_atk1_hh, coreHh(weaponAttack(w, 1)), "flail atk1 hh");
    t.assert(art_dims::flail_atk1_reach, coreReach(weaponAttack(w, 1)), "flail atk1 reach");
    t.assert(art_dims::flail_atk2_hw, coreHw(weaponAttack(w, 2)), "flail atk2 hw");
    t.assert(art_dims::flail_atk2_hh, coreHh(weaponAttack(w, 2)), "flail atk2 hh");
    t.assert(art_dims::flail_atk2_reach, coreReach(weaponAttack(w, 2)), "flail atk2 reach");
    t.assert(art_dims::flail_special_hw, coreHw(weaponSpecial(w)), "flail special hw");
    t.assert(art_dims::flail_special_hh, coreHh(weaponSpecial(w)), "flail special hh");
    t.assert(art_dims::flail_special_reach, coreReach(weaponSpecial(w)), "flail special reach");

    w = &WEAPON_DEFS[2];
    t.assert(art_dims::gunshield_atk0_hw, coreHw(weaponAttack(w, 0)), "gun atk0 hw");
    t.assert(art_dims::gunshield_atk0_hh, coreHh(weaponAttack(w, 0)), "gun atk0 hh");
    t.assert(art_dims::gunshield_atk0_reach, coreReach(weaponAttack(w, 0)), "gun atk0 reach");
    t.assert(art_dims::gunshield_atk1_hw, coreHw(weaponAttack(w, 1)), "gun atk1 hw");
    t.assert(art_dims::gunshield_atk1_hh, coreHh(weaponAttack(w, 1)), "gun atk1 hh");
    t.assert(art_dims::gunshield_atk1_reach, coreReach(weaponAttack(w, 1)), "gun atk1 reach");
    t.assert(art_dims::gunshield_atk2_hw, coreHw(weaponAttack(w, 2)), "gun atk2 hw");
    t.assert(art_dims::gunshield_atk2_hh, coreHh(weaponAttack(w, 2)), "gun atk2 hh");
    t.assert(art_dims::gunshield_atk2_reach, coreReach(weaponAttack(w, 2)), "gun atk2 reach");

    const MonsterAttack *ma = &MONSTER_ATTACKS[0];
    t.assert(art_dims::monster_lunge_hw, monsterAttackHw(ma), "lunge hw");
    t.assert(art_dims::monster_lunge_hh, monsterAttackHh(ma), "lunge hh");
    t.assert(art_dims::monster_lunge_reach, monsterAttackReach(ma), "lunge reach");
    ma = &MONSTER_ATTACKS[1];
    t.assert(art_dims::monster_sweep_hw, monsterAttackHw(ma), "sweep hw");
    t.assert(art_dims::monster_sweep_hh, monsterAttackHh(ma), "sweep hh");
    t.assert(art_dims::monster_sweep_reach, monsterAttackReach(ma), "sweep reach");
}

// -------------------------------------- slash frame layout carries core dims

// The slash frame is 32x32 with the hit box centred and the white 4x4 core on
// the box centre (slash_core_x/y). One frame per distinct sword box, in the
// order the generator authors them.
void testSlashLayout(Test &t) {
    const WeaponDef *w = &WEAPON_DEFS[0];
    const int16_t boxes[5][2] = {
        {coreHw(weaponAttack(w, 0)), coreHh(weaponAttack(w, 0))},
        {coreHw(weaponAttack(w, 2)), coreHh(weaponAttack(w, 2))},
        {coreHw(weaponSpecial(w)), coreHh(weaponSpecial(w))},
        {coreHw(branchAtk(weaponBranch(w, 0))), coreHh(branchAtk(weaponBranch(w, 0)))},
        {coreHw(branchAtk(weaponBranch(w, 1))), coreHh(branchAtk(weaponBranch(w, 1)))},
    };
    for (int i = 0; i < 5; i++) {
        const int x = (art_dims::slash_frame_w - boxes[i][0]) / 2;
        const int y = (art_dims::slash_frame_h - boxes[i][1]) / 2;
        t.assertGreaterThan(x, -1, "slash box x fits");
        t.assertGreaterThan(art_dims::slash_frame_w - (x + boxes[i][0]), -1, "slash box right fits");
        t.assertGreaterThan(y, -1, "slash box y fits");
        t.assertGreaterThan(art_dims::slash_frame_h - (y + boxes[i][1]), -1, "slash box bottom fits");
        t.assert((art_dims::slash_frame_h - boxes[i][1]) % 2, 0, "slash box y centred");
        t.assert((art_dims::slash_frame_w - boxes[i][0]) % 2, 0, "slash box x centred");
        // core centre == box centre == frame centre
        t.assert(x + boxes[i][0] / 2, art_dims::slash_frame_w / 2, "slash box centre x");
        t.assert(y + boxes[i][1] / 2, art_dims::slash_frame_h / 2, "slash box centre y");
        t.assert(art_dims::slash_core_x + art_dims::slash_core_size / 2, art_dims::slash_frame_w / 2, "slash core centre x");
        t.assert(art_dims::slash_core_y + art_dims::slash_core_size / 2, art_dims::slash_frame_h / 2, "slash core centre y");
    }
    // Frame order: combo 12x10, combo 18x14, special 20x16, step-slash 14x12,
    // spin-cut 28x26.
    t.assert(art_dims::sword_atk0_hw, boxes[0][0], "slash f0 box w");
    t.assert(art_dims::sword_atk2_hw, boxes[1][0], "slash f1 box w");
    t.assert(art_dims::sword_special_hw, boxes[2][0], "slash f2 box w");
    t.assert(art_dims::sword_branch0_hw, boxes[3][0], "slash f3 box w");
    t.assert(art_dims::sword_branch1_hw, boxes[4][0], "slash f4 box w");
    t.assert(art_dims::sword_branch1_hh, boxes[4][1], "slash f4 box h");
}

// --------------------------------------------- per-sheet pixel presence

void testSheetPixels(Test &t) {
    Blob slash, ripspecial, parry, whirl, deflect, guard, reload, erase, trail, telegraph, chip, tail;
    if (!parseBlob("fxslash", slash, t) || !parseBlob("fxripspecial", ripspecial, t) || !parseBlob("fxparry", parry, t) || !parseBlob("fxwhirl", whirl, t) || !parseBlob("fxdeflect", deflect, t) ||
        !parseBlob("fxguard", guard, t) || !parseBlob("fxreload", reload, t) || !parseBlob("fxerase", erase, t) || !parseBlob("fxtrail", trail, t) || !parseBlob("fxtelegraph", telegraph, t) ||
        !parseBlob("fxchip", chip, t) || !parseBlob("fxtail", tail, t))
        return;

    // Sheet headers agree with the generated frame layout.
    t.assert(slash.w, art_dims::slash_frame_w, "slash blob frame w");
    t.assert(slash.h, art_dims::slash_frame_h, "slash blob frame h");
    t.assert(slash.frames, art_dims::slash_frames, "slash blob frames");
    t.assert(parry.w, art_dims::parry_frame_w, "parry blob frame w");
    t.assert(parry.h, art_dims::parry_frame_h, "parry blob frame h");
    t.assert(guard.w, art_dims::guard_frame_w, "guard blob frame w");
    t.assert(guard.frames, art_dims::guard_frames, "guard blob frames");
    t.assert(telegraph.w, art_dims::telegraph_frame_w, "telegraph blob frame w");
    t.assert(telegraph.h, art_dims::telegraph_frame_h, "telegraph blob frame h");
    t.assert(telegraph.frames, art_dims::telegraph_frames, "telegraph blob frames");
    t.assert(whirl.frames, art_dims::whirl_frames, "whirl blob frames");
    t.assert(chip.frames, art_dims::chip_frames, "chip blob frames");
    t.assert(tail.w, art_dims::tail_frame_w, "tail blob frame w");
    t.assert(tail.h, art_dims::tail_frame_h, "tail blob frame h");
    t.assert(tail.frames, art_dims::tail_frames, "tail blob frames");

    // Sword slash frames 0..4: light box (hw x hh) centred in the 32x32 frame
    // with the white 4x4 core on the box centre. Frame order: combo 12x10,
    // combo 18x14, special 20x16, step-slash 14x12, spin-cut 28x26.
    const WeaponDef *sword = &WEAPON_DEFS[0];
    const int16_t boxes[5][2] = {
        {coreHw(weaponAttack(sword, 0)), coreHh(weaponAttack(sword, 0))},
        {coreHw(weaponAttack(sword, 2)), coreHh(weaponAttack(sword, 2))},
        {coreHw(weaponSpecial(sword)), coreHh(weaponSpecial(sword))},
        {coreHw(branchAtk(weaponBranch(sword, 0))), coreHh(branchAtk(weaponBranch(sword, 0)))},
        {coreHw(branchAtk(weaponBranch(sword, 1))), coreHh(branchAtk(weaponBranch(sword, 1)))},
    };
    for (int i = 0; i < 5; i++) {
        const int px = (slash.w - boxes[i][0]) / 2;
        const int py = (slash.h - boxes[i][1]) / 2;
        // box top-left pixel: plane0 on, plane1 on, plane2 off (light gray)
        t.assert(bitAt(py % 8, pixelMask(slash, i, 0, px, py / 8)), 1, "slash box mask");
        t.assert(bitAt(py % 8, pixelData(slash, i, 0, px, py / 8)), 1, "slash box plane0 on");
        t.assert(bitAt(py % 8, pixelData(slash, i, 1, px, py / 8)), 1, "slash box plane1 on");
        t.assert(bitAt(py % 8, pixelData(slash, i, 2, px, py / 8)), 0, "slash box plane2 off");
        // white core at the box/frame centre: all planes on
        t.assert(bitAt(art_dims::slash_core_y % 8, pixelData(slash, i, 0, art_dims::slash_core_x, art_dims::slash_core_y / 8)), 1, "slash core plane0");
        t.assert(bitAt(art_dims::slash_core_y % 8, pixelData(slash, i, 2, art_dims::slash_core_x, art_dims::slash_core_y / 8)), 1, "slash core plane2");
        // outside the box (one px left) stays transparent
        t.assert(bitAt(py % 8, pixelMask(slash, i, 0, px - 1, py / 8)), 0, "slash outside box clear");
    }
    // Riposte rim matches the special box + 2 px per side.
    {
        const int rhw = boxes[2][0] + 2 * art_dims::slash_riposte_pad;
        const int rhh = boxes[2][1] + 2 * art_dims::slash_riposte_pad;
        const int rx = (ripspecial.w - rhw) / 2;
        const int ry = (ripspecial.h - rhh) / 2;
        t.assert(bitAt(ry % 8, pixelMask(ripspecial, 0, 0, rx, ry / 8)), 1, "riposte rim mask");
        t.assert(bitAt(ry % 8, pixelData(ripspecial, 0, 1, rx, ry / 8)), 1, "riposte rim light");
        t.assert(bitAt(ry % 8, pixelData(ripspecial, 0, 2, rx, ry / 8)), 0, "riposte rim no white");
    }

    // Parry: white blade bar 2x14 at frame x=11, light-gray cap 6x2 at x=9,y=2.
    t.assert(bitAt(4 % 8, pixelData(parry, 0, 0, 12, 4 / 8)), 1, "parry blade plane0");
    t.assert(bitAt(4 % 8, pixelData(parry, 0, 2, 12, 4 / 8)), 1, "parry blade plane2");
    t.assert(bitAt(2 % 8, pixelData(parry, 0, 1, 10, 2 / 8)), 1, "parry cap plane1");

    // Whirl: frame 0 is a 2x2 light orbit dot, frame 1 a 4x4 white ball,
    // frame 2 a 1x1 light chain dot, frame 3 a 2x2 white stun sparkle.
    t.assert(bitAt(0, pixelData(whirl, art_dims::whirl_dot_frame, 0, 0, 0)), 1, "whirl dot plane0");
    t.assert(bitAt(1, pixelData(whirl, art_dims::whirl_ball_frame, 2, 1, 0)), 1, "whirl ball plane2");
    t.assert(bitAt(0, pixelData(whirl, art_dims::whirl_chain_frame, 0, 0, 0)), 1, "whirl chain dot plane0");
    t.assert(bitAt(0, pixelData(whirl, art_dims::whirl_chain_frame, 1, 0, 0)), 1, "whirl chain dot plane1");
    t.assert(bitAt(0, pixelData(whirl, art_dims::whirl_chain_frame, 2, 0, 0)), 0, "whirl chain dot plane2 off");
    t.assert(bitAt(0, pixelMask(whirl, art_dims::whirl_chain_frame, 0, 1, 0)), 0, "whirl chain dot 1px");
    t.assert(bitAt(0, pixelData(whirl, art_dims::whirl_stun_frame, 2, 0, 0)), 1, "whirl stun plane2");
    t.assert(bitAt(1, pixelData(whirl, art_dims::whirl_stun_frame, 2, 1, 0)), 1, "whirl stun plane2 row1");
    t.assert(bitAt(0, pixelMask(whirl, art_dims::whirl_stun_frame, 0, 2, 0)), 0, "whirl stun 2px wide");
    // Deflect: two light-gray 1x12 bars at the player's left/right edge.
    t.assert(bitAt(2 % 8, pixelData(deflect, 0, 0, 2, 2 / 8)), 1, "deflect left bar plane0");
    t.assert(bitAt(2 % 8, pixelData(deflect, 0, 0, 21, 2 / 8)), 1, "deflect right bar plane0");

    // Gun shield: light plate with a black eraser notch (mask on, all planes
    // off), white guard variant, shove variant one px further out.
    t.assert(bitAt(1 % 8, pixelMask(guard, 0, 0, 5, 1 / 8)), 1, "guard notch mask");
    t.assert(bitAt(1 % 8, pixelData(guard, 0, 0, 5, 1 / 8)), 0, "guard notch plane0 off");
    t.assert(bitAt(1 % 8, pixelData(guard, 0, 1, 5, 1 / 8)), 0, "guard notch plane1 off");
    t.assert(bitAt(1 % 8, pixelData(guard, 0, 0, 2, 1 / 8)), 1, "guard plate plane0");
    t.assert(bitAt(1 % 8, pixelData(guard, 1, 2, 2, 1 / 8)), 1, "guard variant white");
    t.assert(bitAt(1 % 8, pixelData(guard, 2, 2, 1, 1 / 8)), 1, "shove plate white");
    // Reload bar: light 1 px row at frame y=3 (mock x+3, y-3, 10x2).
    t.assert(bitAt(3 % 8, pixelData(reload, 0, 0, 0, 3 / 8)), 1, "reload bar plane0");
    t.assert(bitAt(0, pixelMask(reload, 0, 0, 0, 0)), 0, "reload above bar clear");

    // I-frame erase: 4x1 black eraser (mask on, planes off) and nothing else.
    t.assert(bitAt(0, pixelMask(erase, 0, 0, 0, 0)), 1, "erase mask on");
    t.assert(bitAt(0, pixelData(erase, 0, 0, 0, 0)), 0, "erase plane0 off");
    t.assert(bitAt(0, pixelMask(erase, 0, 0, 0, 1)), 0, "erase below row clear");

    // Trail puffs: frame 0 light gray, frame 1 dark gray.
    t.assert(bitAt(0, pixelData(trail, 0, 0, 0, 0)), 1, "trail puff light plane0");
    t.assert(bitAt(0, pixelData(trail, 1, 0, 0, 0)), 1, "trail puff dark plane0");
    t.assert(bitAt(0, pixelData(trail, 1, 1, 0, 0)), 0, "trail puff dark plane1 off");

    // Telegraph frames 0..3: lunge windup (dark box + 2x2 light core), lunge
    // attack (light box + 4x4 white core), sweep windup and sweep attack. Box
    // and core are centred in the 32x24 frame for both attacks.
    const int lx = art_dims::telegraph_lunge_x;
    const int ly = art_dims::telegraph_lunge_y;
    const int lcx = lx + monHw(&MONSTER_ATTACKS[0]) / 2 - 1;
    const int lcy = ly + monHh(&MONSTER_ATTACKS[0]) / 2 - 1;
    t.assert(bitAt(ly % 8, pixelData(telegraph, 0, 0, lx, ly / 8)), 1, "lunge windup dark");
    t.assert(bitAt(ly % 8, pixelData(telegraph, 0, 1, lx, ly / 8)), 0, "lunge windup not light");
    t.assert(bitAt(lcy % 8, pixelData(telegraph, 0, 1, lcx, lcy / 8)), 1, "lunge windup core light");
    t.assert(bitAt(ly % 8, pixelData(telegraph, 1, 1, lx, ly / 8)), 1, "lunge attack light");
    t.assert(bitAt((lcy - 1) % 8, pixelData(telegraph, 1, 2, lcx - 1, (lcy - 1) / 8)), 1, "lunge attack core white");
    const int sx = art_dims::telegraph_sweep_x;
    const int sy = art_dims::telegraph_sweep_y;
    const int scx = sx + monHw(&MONSTER_ATTACKS[1]) / 2 - 1;
    const int scy = sy + monHh(&MONSTER_ATTACKS[1]) / 2 - 1;
    t.assert(bitAt(sy % 8, pixelData(telegraph, 2, 0, sx, sy / 8)), 1, "sweep windup dark");
    t.assert(bitAt(sy % 8, pixelData(telegraph, 2, 1, sx, sy / 8)), 0, "sweep windup not light");
    t.assert(bitAt(scy % 8, pixelData(telegraph, 2, 1, scx, scy / 8)), 1, "sweep windup core light");
    t.assert(bitAt(sy % 8, pixelData(telegraph, 3, 1, sx, sy / 8)), 1, "sweep attack light");
    t.assert(bitAt((scy - 1) % 8, pixelData(telegraph, 3, 2, scx - 1, (scy - 1) / 8)), 1, "sweep attack core white");

    // Chip: 3x3 white idle/aim chip (frame 0) and 4x4 white ball (frame 1).
    t.assert(bitAt(0, pixelData(chip, art_dims::chip_idle_frame, 2, 0, 0)), 1, "chip idle white");
    t.assert(bitAt(0, pixelData(chip, art_dims::chip_idle_frame, 2, 1, 0)), 1, "chip idle row0 col1");
    t.assert(bitAt(0, pixelMask(chip, art_dims::chip_idle_frame, 0, 3, 0)), 0, "chip idle 3px wide");
    t.assert(bitAt(0, pixelData(chip, art_dims::chip_ball_frame, 2, 1, 0)), 1, "chip ball white");
    t.assert(chip.w, art_dims::chip_frame_w, "chip blob frame w");

    // Breakable-part tail: frames in combatPartArtFrame() order (east intact,
    // east broken, west intact, west broken). Intact frames are a light body
    // (planes 0+1) with a white tip (plane 2); broken frames are a dark stub
    // (plane 0 only) at the body end; the far side stays transparent.
    t.assert(bitAt(2 % 8, pixelMask(tail, 0, 0, 0, 2 / 8)), 1, "tail east intact mask");
    t.assert(bitAt(2 % 8, pixelData(tail, 0, 0, 0, 2 / 8)), 1, "tail east intact plane0");
    t.assert(bitAt(2 % 8, pixelData(tail, 0, 1, 0, 2 / 8)), 1, "tail east intact plane1");
    t.assert(bitAt(2 % 8, pixelData(tail, 0, 2, 0, 2 / 8)), 0, "tail east intact tip is light");
    t.assert(bitAt(3 % 8, pixelData(tail, 0, 2, 0, 3 / 8)), 1, "tail east white tip plane2");
    t.assert(bitAt(2 % 8, pixelMask(tail, 0, 0, 12, 2 / 8)), 0, "tail east far side clear");
    t.assert(bitAt(3 % 8, pixelData(tail, 1, 0, 9, 3 / 8)), 1, "tail east broken stub plane0");
    t.assert(bitAt(3 % 8, pixelData(tail, 1, 1, 9, 3 / 8)), 0, "tail east broken stub dark only");
    t.assert(bitAt(2 % 8, pixelMask(tail, 1, 0, 0, 2 / 8)), 0, "tail east broken clears the tip");
    t.assert(bitAt(2 % 8, pixelData(tail, 2, 0, 6, 2 / 8)), 1, "tail west intact plane0");
    t.assert(bitAt(3 % 8, pixelData(tail, 2, 2, 15, 3 / 8)), 1, "tail west white tip plane2");
    t.assert(bitAt(2 % 8, pixelMask(tail, 2, 0, 0, 2 / 8)), 0, "tail west near side clear");
    t.assert(bitAt(3 % 8, pixelData(tail, 3, 0, 0, 3 / 8)), 1, "tail west broken stub plane0");
    t.assert(bitAt(3 % 8, pixelData(tail, 3, 1, 0, 3 / 8)), 0, "tail west broken stub dark only");
    t.assert(bitAt(3 % 8, pixelMask(tail, 3, 0, 9, 3 / 8)), 0, "tail west broken clears the tip");

    // Frame coverage: every declared frame of every new sheet is parsed, so a
    // truncated Sprites.txt (stale append) cannot silently skip an icon.
    t.assert(slash.frames, art_dims::slash_frames, "slash frames parsed");
    t.assert(ripspecial.frames, art_dims::ripspecial_frames, "riposte frames parsed");
    t.assert(parry.frames, art_dims::parry_frames, "parry frames parsed");
    t.assert(whirl.frames, art_dims::whirl_frames, "whirl frames parsed");
    t.assert(deflect.frames, art_dims::deflect_frames, "deflect frames parsed");
    t.assert(guard.frames, art_dims::guard_frames, "guard frames parsed");
    t.assert(reload.frames, art_dims::reload_frames, "reload frames parsed");
    t.assert(erase.frames, art_dims::erase_frames, "erase frames parsed");
    t.assert(trail.frames, art_dims::trail_frames, "trail frames parsed");
    t.assert(telegraph.frames, art_dims::telegraph_frames, "telegraph frames parsed");
    t.assert(chip.frames, art_dims::chip_frames, "chip frames parsed");
    t.assert(tail.frames, art_dims::tail_frames, "tail frames parsed");
}

// ------------------------------------------- demo beast sheets (epic nch)

// FNV-1a over one frame's plus-mask bytes; the plane passes are included, so
// two frames match only when every pixel/shade matches.
uint32_t blobFrameHash(const Blob &b, int frame) {
    const int frame_bytes = ((b.h + 7) / 8) * b.w * 3 * 2;
    uint32_t h = 2166136261u;
    for (int i = 0; i < frame_bytes; i++) {
        h ^= static_cast<uint32_t>(b.bytes[frame * frame_bytes + i]);
        h *= 16777619u;
    }
    return h;
}

int maskAt(const Blob &b, int x, int y) {
    return bitAt(y, pixelMask(b, 0, 0, x, y / 8));
}
int planeAt(const Blob &b, int shade, int x, int y) {
    return bitAt(y, pixelData(b, 0, shade, x, y / 8));
}

// The three demo beasts ship 32x24x8 sheets with distinct silhouettes; RAVAGER
// keeps the legacy fxmonster. Checks the frame layout, that frame 0 (east idle)
// differs across beasts and from its own west frame, and the signature
// features (crest / two legs, four legs + horns, thick tail).
void testMonsterSheets(Test &t) {
    std::cout << "---------- demo beast sheets distinct ----------" << std::endl;
    Blob chicken, bull, longtail, ravager;
    if (!parseBlob("fxmonster_lunge", chicken, t) || !parseBlob("fxmonster_sweep", bull, t) || !parseBlob("fxmonster_heavy", longtail, t) || !parseBlob("fxmonster", ravager, t))
        return;
    for (const Blob *b : {&chicken, &bull, &longtail, &ravager}) {
        t.assert(b->w, 32, "beast sheet w");
        t.assert(b->h, 24, "beast sheet h");
        t.assert(b->frames, 8, "beast sheet frames");
    }
    // Frame 0 (east idle) is unique per beast and mirrored for west (frame 4).
    const uint32_t hc = blobFrameHash(chicken, 0), hb = blobFrameHash(bull, 0), hl = blobFrameHash(longtail, 0);
    t.assert(hc != hb ? 1 : 0, 1, "chicken != bull frame 0");
    t.assert(hc != hl ? 1 : 0, 1, "chicken != longtail frame 0");
    t.assert(hb != hl ? 1 : 0, 1, "bull != longtail frame 0");
    t.assert(blobFrameHash(chicken, 0) != blobFrameHash(chicken, 4) ? 1 : 0, 1, "chicken east != west");

    // Chicken: layered tail plumes fill the left of the cell (body plane0 at
    // (2,6) and (2,10)); two separated dark legs with a clear gap; a white comb
    // above the head; a black eye inside the white head; a black beak.
    t.assert(planeAt(chicken, 0, 2, 6), 1, "chicken upper tail plume");
    t.assert(planeAt(chicken, 0, 2, 10), 1, "chicken tail plume body");
    t.assert(maskAt(chicken, 11, 20), 1, "chicken near leg");
    t.assert(maskAt(chicken, 16, 20), 1, "chicken far leg");
    t.assert(maskAt(chicken, 14, 20), 0, "chicken clear between legs");
    t.assert(maskAt(chicken, 4, 20), 0, "chicken no outer leg");
    t.assert(planeAt(chicken, 2, 22, 0), 1, "chicken comb white");
    t.assert(planeAt(chicken, 2, 24, 4), 0, "chicken eye not white");
    t.assert(maskAt(chicken, 24, 4), 1, "chicken eye ink");
    t.assert(maskAt(chicken, 30, 5), 1, "chicken beak ink");

    // Bull: a hanging tail (body plane0 at (1,10)); four separated dark legs
    // with a clear gap; two white horns above the low head; the broad body
    // plane0 at (10,10); a black eye inside the head.
    t.assert(planeAt(bull, 0, 1, 10), 1, "bull tail");
    t.assert(maskAt(bull, 5, 20), 1, "bull leg 1");
    t.assert(maskAt(bull, 10, 20), 1, "bull leg 2");
    t.assert(maskAt(bull, 19, 20), 1, "bull leg 3");
    t.assert(maskAt(bull, 24, 20), 1, "bull leg 4");
    t.assert(maskAt(bull, 15, 20), 0, "bull clear between legs");
    t.assert(planeAt(bull, 2, 24, 6), 1, "bull near horn");
    t.assert(planeAt(bull, 2, 29, 6), 1, "bull far horn");
    t.assert(planeAt(bull, 0, 10, 10), 1, "bull broad body");
    t.assert(maskAt(bull, 25, 12), 1, "bull eye ink");
    t.assert(planeAt(bull, 2, 25, 12), 0, "bull eye not white");

    // Longtail: a thick segmented tail fills the left of the cell (plane0 at
    // (2,6) and (2,10)) with a dark segment line; four separated legs; a
    // forward white head; a dark jaw line under the snout.
    t.assert(planeAt(longtail, 0, 2, 6), 1, "longtail ridge spike");
    t.assert(planeAt(longtail, 0, 2, 10), 1, "longtail tail body");
    t.assert(planeAt(longtail, 0, 3, 10), 0, "longtail tail segment line");
    t.assert(maskAt(longtail, 10, 20), 1, "longtail leg 1");
    t.assert(maskAt(longtail, 15, 20), 1, "longtail leg 2");
    t.assert(maskAt(longtail, 20, 20), 1, "longtail leg 3");
    t.assert(maskAt(longtail, 25, 20), 1, "longtail leg 4");
    t.assert(maskAt(longtail, 13, 20), 0, "longtail clear between legs");
    t.assert(planeAt(longtail, 2, 22, 6), 1, "longtail forward head");
    t.assert(maskAt(longtail, 28, 11), 1, "longtail jaw ink");
    t.assert(planeAt(longtail, 2, 28, 11), 0, "longtail jaw not white");
}

void ArtDimsSuite(TestRunner &runner) {
    TestSuite suite("art dims");
    {
        Test t("core dims mirrored into art_dims.hpp");
        testCoreDimMirrors(t);
        suite.addTest(t);
    }
    {
        Test t("slash frames carry the core hit box");
        testSlashLayout(t);
        suite.addTest(t);
    }
    {
        Test t("overlay/effect sheets carry core-sized ink");
        testSheetPixels(t);
        suite.addTest(t);
    }
    {
        Test t("demo beast sheets read as distinct silhouettes");
        testMonsterSheets(t);
        suite.addTest(t);
    }
    runner.addTestSuite(suite);
}

}   // namespace artdimstest
