#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfcf1;
constexpr uint24_t FX_DATA_BYTES = 200437;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x0003DB;
constexpr uint24_t mhMonsterDefs = 0x0003FD;
constexpr uint24_t mhSin65 = 0x000429;
constexpr uint24_t mhCombat = 0x00046A;
constexpr uint24_t mhEquip = 0x0008AF;
constexpr uint24_t mhScreens = 0x000C1B;
constexpr uint24_t mhQuests = 0x000E51;
constexpr uint24_t mhSmith = 0x000E7D;
constexpr uint24_t mhZones = 0x000EEF;
constexpr uint24_t mhItems = 0x000FE8;
constexpr uint24_t mhArmor = 0x001018;
constexpr uint24_t fxtail = 0x001089;
constexpr uint24_t fxdeflect = 0x0013EB;
constexpr uint24_t fxtail_spin = 0x00150D;
constexpr uint24_t fxtailspin = 0x001BCF;
constexpr uint24_t fxparry = 0x004151;
constexpr uint24_t fxmonster = 0x004273;
constexpr uint24_t fxchip = 0x005475;
constexpr uint24_t fxpole = 0x0054D7;
constexpr uint24_t mh_map_tent = 0x005989;
constexpr uint24_t fxguard = 0x005BCB;
constexpr uint24_t fxmonster_sweep = 0x005D7D;
constexpr uint24_t fxwhirlring = 0x007CFF;
constexpr uint24_t fxspark = 0x00E901;
constexpr uint24_t fxmonster_lunge = 0x00E933;
constexpr uint24_t fxball = 0x0108B5;
constexpr uint24_t fxchickenatk = 0x0108E1;
constexpr uint24_t fxmonster_heavy = 0x011663;
constexpr uint24_t fxbullatk = 0x0135E5;
constexpr uint24_t fxhooves_bull = 0x0147E7;
constexpr uint24_t fxtrail = 0x014BA9;
constexpr uint24_t fxwhirl = 0x014BDB;
constexpr uint24_t fxhead_chicken = 0x014C9D;
constexpr uint24_t fxplayer = 0x014DA7;
constexpr uint24_t fxripspecial = 0x014F29;
constexpr uint24_t fxheavyatk = 0x0150DB;
constexpr uint24_t fxtail_heavy = 0x0162DD;
constexpr uint24_t fxhead_bull = 0x01675F;
constexpr uint24_t fxpole_crack = 0x0169A1;
constexpr uint24_t fxlegs_chicken = 0x017A83;
constexpr uint24_t fxpole_break = 0x017D0D;
constexpr uint24_t fxreload = 0x018DEF;
constexpr uint24_t fxscatter = 0x018E2D;
constexpr uint24_t fxpole_sever = 0x018E47;
constexpr uint24_t fxerase = 0x019F29;
constexpr uint24_t fxhud = 0x019F5B;
constexpr uint24_t fxslash = 0x01A19D;
constexpr uint24_t fxfontg = 0x01B09F;
constexpr uint24_t fxfontw = 0x01BCA1;
constexpr uint24_t mh_head_bandana = 0x01C8A3;
constexpr uint24_t mh_weapon_sword = 0x01CEA5;
constexpr uint24_t mh_head_helm = 0x0216A7;
constexpr uint24_t mh_player_base = 0x021CA9;
constexpr uint24_t mh_body_base = 0x0222AB;
constexpr uint24_t mh_shadow_base = 0x022EAD;
constexpr uint24_t mh_weapon_gun = 0x022F6F;
constexpr uint24_t mh_head_base = 0x027771;
constexpr uint24_t mh_weapon_flail = 0x027D73;
constexpr uint24_t mh_map_area = 0x02C575;
constexpr uint24_t mh_map_camp = 0x030475;
