#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfce2;
constexpr uint24_t FX_DATA_BYTES = 204162;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x0003DB;
constexpr uint24_t mhMonsterDefs = 0x0003FD;
constexpr uint24_t mhSin65 = 0x000429;
constexpr uint24_t mhCombat = 0x00046A;
constexpr uint24_t mhEquip = 0x00086E;
constexpr uint24_t mhScreens = 0x000BDA;
constexpr uint24_t mhQuests = 0x000CF6;
constexpr uint24_t mhSmith = 0x000D10;
constexpr uint24_t mhZones = 0x000D42;
constexpr uint24_t fxtail = 0x000DD2;
constexpr uint24_t fxdeflect = 0x001134;
constexpr uint24_t fxtail_spin = 0x001256;
constexpr uint24_t fxtailspin = 0x001918;
constexpr uint24_t fxparry = 0x003E9A;
constexpr uint24_t fxmonster = 0x003FBC;
constexpr uint24_t fxchip = 0x0051BE;
constexpr uint24_t fxpole = 0x005220;
constexpr uint24_t mh_map_tent = 0x0056D2;
constexpr uint24_t fxguard = 0x005914;
constexpr uint24_t fxmonster_sweep = 0x005AC6;
constexpr uint24_t fxwhirlring = 0x007A48;
constexpr uint24_t fxspark = 0x00E64A;
constexpr uint24_t fxmonster_lunge = 0x00E67C;
constexpr uint24_t fxball = 0x0105FE;
constexpr uint24_t fxchickenatk = 0x01062A;
constexpr uint24_t fxmonster_heavy = 0x010F2C;
constexpr uint24_t fxbullatk = 0x012EAE;
constexpr uint24_t fxhooves_bull = 0x0137B0;
constexpr uint24_t fxtrail = 0x013B72;
constexpr uint24_t fxwhirl = 0x013BA4;
constexpr uint24_t fxhead_chicken = 0x013C66;
constexpr uint24_t fxplayer = 0x013D70;
constexpr uint24_t fxripspecial = 0x013EF2;
constexpr uint24_t fxtail_heavy = 0x0140A4;
constexpr uint24_t fxhead_bull = 0x014526;
constexpr uint24_t fxpole_crack = 0x014768;
constexpr uint24_t fxlegs_chicken = 0x01584A;
constexpr uint24_t fxpole_break = 0x015AD4;
constexpr uint24_t fxreload = 0x016BB6;
constexpr uint24_t fxscatter = 0x016BF4;
constexpr uint24_t fxpole_sever = 0x016C0E;
constexpr uint24_t fxerase = 0x017CF0;
constexpr uint24_t fxhud = 0x017D22;
constexpr uint24_t fxslash = 0x017F64;
constexpr uint24_t fxfontg = 0x018E66;
constexpr uint24_t fxfontw = 0x019A68;
constexpr uint24_t mh_menu_wsel = 0x01A66A;
constexpr uint24_t mh_menu_msel = 0x01A8AC;
constexpr uint24_t mh_menu_bg = 0x01B4AE;
constexpr uint24_t mh_head_bandana = 0x01CCB0;
constexpr uint24_t mh_weapon_sword = 0x01D2B2;
constexpr uint24_t mh_head_helm = 0x021AB4;
constexpr uint24_t mh_player_base = 0x0220B6;
constexpr uint24_t mh_body_base = 0x0226B8;
constexpr uint24_t mh_shadow_base = 0x0232BA;
constexpr uint24_t mh_weapon_gun = 0x02337C;
constexpr uint24_t mh_head_base = 0x027B7E;
constexpr uint24_t mh_weapon_flail = 0x028180;
constexpr uint24_t mh_map_area = 0x02C982;
constexpr uint24_t mh_map_camp = 0x030882;
constexpr uint24_t mh_map_pole_room = 0x031302;
