#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfce2;
constexpr uint24_t FX_DATA_BYTES = 204210;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x0003DB;
constexpr uint24_t mhMonsterDefs = 0x0003FD;
constexpr uint24_t mhSin65 = 0x000429;
constexpr uint24_t mhCombat = 0x00046A;
constexpr uint24_t mhEquip = 0x00089E;
constexpr uint24_t mhScreens = 0x000C0A;
constexpr uint24_t mhQuests = 0x000D26;
constexpr uint24_t mhSmith = 0x000D40;
constexpr uint24_t mhZones = 0x000D72;
constexpr uint24_t fxtail = 0x000E02;
constexpr uint24_t fxdeflect = 0x001164;
constexpr uint24_t fxtail_spin = 0x001286;
constexpr uint24_t fxtailspin = 0x001948;
constexpr uint24_t fxparry = 0x003ECA;
constexpr uint24_t fxmonster = 0x003FEC;
constexpr uint24_t fxchip = 0x0051EE;
constexpr uint24_t fxpole = 0x005250;
constexpr uint24_t mh_map_tent = 0x005702;
constexpr uint24_t fxguard = 0x005944;
constexpr uint24_t fxmonster_sweep = 0x005AF6;
constexpr uint24_t fxwhirlring = 0x007A78;
constexpr uint24_t fxspark = 0x00E67A;
constexpr uint24_t fxmonster_lunge = 0x00E6AC;
constexpr uint24_t fxball = 0x01062E;
constexpr uint24_t fxchickenatk = 0x01065A;
constexpr uint24_t fxmonster_heavy = 0x010F5C;
constexpr uint24_t fxbullatk = 0x012EDE;
constexpr uint24_t fxhooves_bull = 0x0137E0;
constexpr uint24_t fxtrail = 0x013BA2;
constexpr uint24_t fxwhirl = 0x013BD4;
constexpr uint24_t fxhead_chicken = 0x013C96;
constexpr uint24_t fxplayer = 0x013DA0;
constexpr uint24_t fxripspecial = 0x013F22;
constexpr uint24_t fxtail_heavy = 0x0140D4;
constexpr uint24_t fxhead_bull = 0x014556;
constexpr uint24_t fxpole_crack = 0x014798;
constexpr uint24_t fxlegs_chicken = 0x01587A;
constexpr uint24_t fxpole_break = 0x015B04;
constexpr uint24_t fxreload = 0x016BE6;
constexpr uint24_t fxscatter = 0x016C24;
constexpr uint24_t fxpole_sever = 0x016C3E;
constexpr uint24_t fxerase = 0x017D20;
constexpr uint24_t fxhud = 0x017D52;
constexpr uint24_t fxslash = 0x017F94;
constexpr uint24_t fxfontg = 0x018E96;
constexpr uint24_t fxfontw = 0x019A98;
constexpr uint24_t mh_menu_wsel = 0x01A69A;
constexpr uint24_t mh_menu_msel = 0x01A8DC;
constexpr uint24_t mh_menu_bg = 0x01B4DE;
constexpr uint24_t mh_head_bandana = 0x01CCE0;
constexpr uint24_t mh_weapon_sword = 0x01D2E2;
constexpr uint24_t mh_head_helm = 0x021AE4;
constexpr uint24_t mh_player_base = 0x0220E6;
constexpr uint24_t mh_body_base = 0x0226E8;
constexpr uint24_t mh_shadow_base = 0x0232EA;
constexpr uint24_t mh_weapon_gun = 0x0233AC;
constexpr uint24_t mh_head_base = 0x027BAE;
constexpr uint24_t mh_weapon_flail = 0x0281B0;
constexpr uint24_t mh_map_area = 0x02C9B2;
constexpr uint24_t mh_map_camp = 0x0308B2;
constexpr uint24_t mh_map_pole_room = 0x031332;
