#!/usr/bin/env python3
"""Compile lawless the item-id list into a generated C header.

    data/items.json
        -> src/generated/items_ids.hpp   (item::ID_<NAME> + ID_COUNT)

The full item schema lives in tools/gen-items.py, which authors the packed
mhItems blob + items_meta.hpp. This tiny sibling exists so a tool/header that
needs *only* the id vocabulary (schema validation, recipe cross-refs, the
compile-time material-name whitelist) does not depend on the packed blob's
offsets: the ids are the source-order contract and never move without a regen.

Usage:
    python3 tools/gen-items-ids.py [--root DIR] [--dump]

    --root DIR  pipeline root holding data/ and src/generated (default: repo)
    --dump      print the id table on stdout; writes nothing
"""
import argparse
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_REL = "data/items.json"
META_REL = "src/generated/items_ids.hpp"

NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def load_json(path, rel):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def read_ids(root):
    with open(os.path.join(root, DATA_REL), encoding="utf-8") as handle:
        doc = json.load(handle)
    raw = doc.get("items")
    if not isinstance(doc.get("version"), int):
        raise SystemExit("%s: version must be an integer" % DATA_REL)
    if not isinstance(raw, list) or not raw:
        raise SystemExit("%s: items must be a non-empty array" % DATA_REL)
    ids = []
    for i, obj in enumerate(raw):
        if not isinstance(obj, dict) or not isinstance(obj.get("id"), str) or not NAME_RE.match(obj["id"]):
            raise SystemExit("%s: items[%d].id must match [a-z][a-z0-9_]*" % (DATA_REL, i))
        ids.append(obj["id"])
    return ids


def emit(ids):
    lines = []
    app = lines.append
    app("#pragma once")
    app("// Generated by tools/gen-items-ids.py -- do not edit.")
    app("//")
    app("// Item-id vocabulary only (no blob offsets): item::ID_<NAME> is the")
    app("// source-order index in data/items.json, matching items_meta.hpp's")
    app("// ITEM_<NAME> and Game::items[] slot. Tools and schema checks that must")
    app("// not depend on the packed mhItems layout include this header.")
    app("")
    app("#include <stdint.h>")
    app("")
    app("namespace item_ids {")
    app("")
    app("constexpr uint8_t ID_COUNT = %d;" % len(ids))
    for i, name in enumerate(ids):
        app("constexpr uint8_t ID_%s = %d;" % (name.upper(), i))
    app("")
    app("}   // namespace item_ids")
    app("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=None, help="pipeline root holding data/ (default: repository root)")
    parser.add_argument("--dump", action="store_true", help="print the ids; write nothing")
    args = parser.parse_args(argv)
    root = os.path.abspath(args.root) if args.root else REPO_ROOT
    ids = read_ids(root)
    text = emit(ids)
    if args.dump:
        for i, name in enumerate(ids):
            print("item_ids: %d %s" % (i, name))
        print("gen-items-ids: %d ids" % len(ids))
        return 0
    path = os.path.join(root, META_REL)
    data = text.encode("utf-8")
    if os.path.isfile(path):
        with open(path, "rb") as handle:
            if handle.read() == data:
                print("gen-items-ids: %d ids" % len(ids))
                print("gen-items-ids: %s (unchanged)" % META_REL)
                return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(data)
    print("gen-items-ids: %d ids" % len(ids))
    print("gen-items-ids: %s" % META_REL)
    return 0


if __name__ == "__main__":
    sys.exit(main())
