#!/usr/bin/env python3
"""Emit the creature art sheet address table from the packed FX image.

    data/art_sheets.json + src/fxdata.h
        -> src/generated/art_sheets.hpp

The constructor of this chain is `tools/gen-combat.py`: it validates every
creature's `art.sheet` name against data/art_sheets.json and packs the 1-based
index into the combat blob's ART section. This tool runs POST-pack (after
`fxdata-build.py` has written src/fxdata.h) so the address table is never stale:
it resolves each listed sheet name to the live `constexpr uint24_t <name>` cart
address and emits

    ART_SHEET_<NAME>      1-based index into the table (== art record value)
    ART_SHEETS_COUNT      number of sheets
    ART_SHEET_ADDR_<NAME> host-readable u24 address (uint32 literal)
    ART_SHEETS[]          PROGMEM u24 address table in list order (device only)

with a static_assert per entry pinning the table to the named fxdata constant,
so a repack that moves a sheet fails the build instead of blitting garbage.

Usage:
    python3 tools/gen-art-sheets.py [--root DIR] [--dump]

    --root DIR  pipeline root holding data/, src/fxdata.h, src/generated
    --dump      print the resolved table; write nothing
"""
import argparse
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHEETS_REL = "data/art_sheets.json"
FXDATA_H_REL = "src/fxdata.h"
META_REL = "src/generated/art_sheets.hpp"

NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
# fxdata-build.py emits: constexpr uint24_t <name> = 0xNNNNNN;
SYMBOL_RE = re.compile(r"^constexpr\s+uint24_t\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+);\s*$")


def load_sheets(root):
    path = os.path.join(root, SHEETS_REL)
    try:
        with open(path, encoding="utf-8") as handle:
            doc = json.load(handle)
    except OSError as exc:
        raise SystemExit("%s: cannot read: %s" % (SHEETS_REL, exc))
    except ValueError as exc:
        raise SystemExit("%s: invalid JSON: %s" % (SHEETS_REL, exc))
    if not isinstance(doc, dict) or doc.get("version") != 1:
        raise SystemExit("%s: version must be 1" % SHEETS_REL)
    raw = doc.get("sheets")
    if not isinstance(raw, list) or not raw:
        raise SystemExit("%s: sheets must be a non-empty array" % SHEETS_REL)
    names = []
    seen = set()
    for i, name in enumerate(raw):
        if not isinstance(name, str) or not NAME_RE.match(name):
            raise SystemExit("%s: sheets[%d] must match [a-z][a-z0-9_]*" % (SHEETS_REL, i))
        if name in seen:
            raise SystemExit("%s: duplicate sheet '%s'" % (SHEETS_REL, name))
        seen.add(name)
        names.append(name)
    return names


def load_fxdata_symbols(root):
    path = os.path.join(root, FXDATA_H_REL)
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError as exc:
        raise SystemExit("%s: cannot read: %s (run the packer first)" % (FXDATA_H_REL, exc))
    symbols = {}
    for line in text.splitlines():
        match = SYMBOL_RE.match(line.strip())
        if match:
            symbols[match.group(1)] = int(match.group(2), 16)
    return symbols


def emit(names, addresses):
    lines = []
    app = lines.append
    app("#pragma once")
    app("// Generated by tools/gen-art-sheets.py -- do not edit.")
    app("//")
    app("// Creature art sheet table (epic monhun-ardu-bih): data/art_sheets.json")
    app("// lists the ordered sheet names; the combat blob's ART record stores a")
    app("// 1-based index into this table (0 = none -> legacy per-kind draw).")
    app("// Addresses resolve from the committed src/fxdata.h AFTER the pack, so a")
    app("// repack that moves a sheet fails the static_assert below instead of")
    app("// blitting garbage. Host builds use ART_SHEET_ADDR_<NAME> (uint32).")
    app("")
    app("#include <stdint.h>")
    app("#if defined(__AVR__)")
    app("#include \"../core/progmem.hpp\"   // MH_PROGMEM")
    app("#include \"../fxdata.h\"   // live sheet symbols for the address table")
    app("#endif")
    app("")
    app("namespace art_sheets {")
    app("")
    app("constexpr uint8_t ART_SHEETS_COUNT = %d;" % len(names))
    for i, name in enumerate(names):
        app("constexpr uint8_t ART_SHEET_%s = %d;" % (name.upper(), i + 1))
    app("")
    app("// Host-readable u24 addresses (list order), for the address-table tests.")
    for name in names:
        app("constexpr uint32_t ART_SHEET_ADDR_%s = 0x%06X;" % (name.upper(), addresses[name]))
    app("")
    app("#if defined(__AVR__)")
    app("// Cart sheet addresses in list order: index = ART_SHEET_<NAME> - 1.")
    app("MH_PROGMEM constexpr uint24_t ART_SHEETS[ART_SHEETS_COUNT] = {")
    for name in names:
        app("    %s," % name)
    app("};")
    for i, name in enumerate(names):
        app("static_assert(ART_SHEETS[%d] == %s, \"art sheet %s stale: re-run make gen\");"
            % (i, name, name))
    app("#endif")
    app("")
    app("}   // namespace art_sheets")
    app("")
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=None, help="pipeline root (default: repo)")
    parser.add_argument("--dump", action="store_true", help="print the table; writes nothing")
    args = parser.parse_args(argv)
    root = os.path.abspath(args.root) if args.root else REPO_ROOT
    names = load_sheets(root)
    symbols = load_fxdata_symbols(root)
    addresses = {}
    for name in names:
        if name not in symbols:
            raise SystemExit("%s: sheet '%s' is not declared in %s" % (SHEETS_REL, name, FXDATA_H_REL))
        addresses[name] = symbols[name]
    if args.dump:
        for i, name in enumerate(names):
            print("art_sheets: %d %s 0x%06X" % (i + 1, name, addresses[name]))
        print("gen-art-sheets: %d sheets" % len(names))
        return 0
    path = os.path.join(root, META_REL)
    data = emit(names, addresses).encode("utf-8")
    if os.path.isfile(path):
        with open(path, "rb") as handle:
            if handle.read() == data:
                print("gen-art-sheets: %d sheets" % len(names))
                print("gen-art-sheets: %s (unchanged)" % META_REL)
                return 0
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(data)
    print("gen-art-sheets: %d sheets" % len(names))
    print("gen-art-sheets: %s" % META_REL)
    return 0


if __name__ == "__main__":
    sys.exit(main())
