#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfcf2;
constexpr uint24_t FX_DATA_BYTES = 200067;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x0003DB;
constexpr uint24_t mhMonsterDefs = 0x0003FD;
constexpr uint24_t mhSin65 = 0x000429;
constexpr uint24_t mhCombat = 0x00046A;
constexpr uint24_t mhEquip = 0x0008AF;
constexpr uint24_t mhScreens = 0x000C1B;
constexpr uint24_t mhQuests = 0x000D37;
constexpr uint24_t mhSmith = 0x000D51;
constexpr uint24_t mhZones = 0x000D83;
constexpr uint24_t mhItems = 0x000E23;
constexpr uint24_t fxtail = 0x000E53;
constexpr uint24_t fxdeflect = 0x0011B5;
constexpr uint24_t fxtail_spin = 0x0012D7;
constexpr uint24_t fxtailspin = 0x001999;
constexpr uint24_t fxparry = 0x003F1B;
constexpr uint24_t fxmonster = 0x00403D;
constexpr uint24_t fxchip = 0x00523F;
constexpr uint24_t fxpole = 0x0052A1;
constexpr uint24_t mh_map_tent = 0x005753;
constexpr uint24_t fxguard = 0x005995;
constexpr uint24_t fxmonster_sweep = 0x005B47;
constexpr uint24_t fxwhirlring = 0x007AC9;
constexpr uint24_t fxspark = 0x00E6CB;
constexpr uint24_t fxmonster_lunge = 0x00E6FD;
constexpr uint24_t fxball = 0x01067F;
constexpr uint24_t fxchickenatk = 0x0106AB;
constexpr uint24_t fxmonster_heavy = 0x010FAD;
constexpr uint24_t fxbullatk = 0x012F2F;
constexpr uint24_t fxhooves_bull = 0x013831;
constexpr uint24_t fxtrail = 0x013BF3;
constexpr uint24_t fxwhirl = 0x013C25;
constexpr uint24_t fxhead_chicken = 0x013CE7;
constexpr uint24_t fxplayer = 0x013DF1;
constexpr uint24_t fxripspecial = 0x013F73;
constexpr uint24_t fxtail_heavy = 0x014125;
constexpr uint24_t fxhead_bull = 0x0145A7;
constexpr uint24_t fxpole_crack = 0x0147E9;
constexpr uint24_t fxlegs_chicken = 0x0158CB;
constexpr uint24_t fxpole_break = 0x015B55;
constexpr uint24_t fxreload = 0x016C37;
constexpr uint24_t fxscatter = 0x016C75;
constexpr uint24_t fxpole_sever = 0x016C8F;
constexpr uint24_t fxerase = 0x017D71;
constexpr uint24_t fxhud = 0x017DA3;
constexpr uint24_t fxslash = 0x017FE5;
constexpr uint24_t fxfontg = 0x018EE7;
constexpr uint24_t fxfontw = 0x019AE9;
constexpr uint24_t mh_menu_wsel = 0x01A6EB;
constexpr uint24_t mh_menu_msel = 0x01A92D;
constexpr uint24_t mh_menu_bg = 0x01AF2F;
constexpr uint24_t mh_head_bandana = 0x01C731;
constexpr uint24_t mh_weapon_sword = 0x01CD33;
constexpr uint24_t mh_head_helm = 0x021535;
constexpr uint24_t mh_player_base = 0x021B37;
constexpr uint24_t mh_body_base = 0x022139;
constexpr uint24_t mh_shadow_base = 0x022D3B;
constexpr uint24_t mh_weapon_gun = 0x022DFD;
constexpr uint24_t mh_head_base = 0x0275FF;
constexpr uint24_t mh_weapon_flail = 0x027C01;
constexpr uint24_t mh_map_area = 0x02C403;
constexpr uint24_t mh_map_camp = 0x030303;
