#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfdb4;
constexpr uint24_t FX_DATA_BYTES = 150377;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x00021C;
constexpr uint24_t mhMonsterDefs = 0x00023E;
constexpr uint24_t mhSin65 = 0x00026A;
constexpr uint24_t mhCombat = 0x0002AB;
constexpr uint24_t mhEquip = 0x00056B;
constexpr uint24_t mhScreens = 0x0008D7;
constexpr uint24_t mhQuests = 0x0009F3;
constexpr uint24_t mhSmith = 0x000A0D;
constexpr uint24_t fxtail = 0x000A3F;
constexpr uint24_t fxdeflect = 0x000DA1;
constexpr uint24_t fxtail_spin = 0x000EC3;
constexpr uint24_t fxparry = 0x001585;
constexpr uint24_t fxmonster = 0x0016A7;
constexpr uint24_t fxchip = 0x0028A9;
constexpr uint24_t fxpole = 0x00290B;
constexpr uint24_t fxguard = 0x002DBD;
constexpr uint24_t fxmonster_sweep = 0x002F6F;
constexpr uint24_t fxwhirlring = 0x004EF1;
constexpr uint24_t fxspark = 0x00BAF3;
constexpr uint24_t fxmonster_lunge = 0x00BB25;
constexpr uint24_t fxball = 0x00DAA7;
constexpr uint24_t fxmonster_heavy = 0x00DAD3;
constexpr uint24_t fxtrail = 0x00FA55;
constexpr uint24_t fxwhirl = 0x00FA87;
constexpr uint24_t fxplayer = 0x00FB49;
constexpr uint24_t fxripspecial = 0x00FCCB;
constexpr uint24_t fxtail_heavy = 0x00FE7D;
constexpr uint24_t fxreload = 0x0102FF;
constexpr uint24_t fxscatter = 0x01033D;
constexpr uint24_t fxerase = 0x010357;
constexpr uint24_t fxhud = 0x010389;
constexpr uint24_t fxslash = 0x0105CB;
constexpr uint24_t fxfontg = 0x0114CD;
constexpr uint24_t fxfontw = 0x0120CF;
constexpr uint24_t mh_menu_wsel = 0x012CD1;
constexpr uint24_t mh_menu_msel = 0x012F13;
constexpr uint24_t mh_menu_bg = 0x013695;
constexpr uint24_t mh_head_bandana = 0x014E97;
constexpr uint24_t mh_weapon_sword = 0x015499;
constexpr uint24_t mh_head_helm = 0x019C9B;
constexpr uint24_t mh_player_base = 0x01A29D;
constexpr uint24_t mh_body_base = 0x01A89F;
constexpr uint24_t mh_shadow_base = 0x01B4A1;
constexpr uint24_t mh_weapon_gun = 0x01B563;
constexpr uint24_t mh_head_base = 0x01FD65;
constexpr uint24_t mh_weapon_flail = 0x020367;
