#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfce1;
constexpr uint24_t FX_DATA_BYTES = 204435;

constexpr uint24_t mhWeaponDefs = 0x000000;
constexpr uint24_t mhMonsterAttacks = 0x0003DB;
constexpr uint24_t mhMonsterDefs = 0x0003FD;
constexpr uint24_t mhSin65 = 0x000429;
constexpr uint24_t mhCombat = 0x00046A;
constexpr uint24_t mhEquip = 0x00097F;
constexpr uint24_t mhScreens = 0x000CEB;
constexpr uint24_t mhQuests = 0x000E07;
constexpr uint24_t mhSmith = 0x000E21;
constexpr uint24_t mhZones = 0x000E53;
constexpr uint24_t fxtail = 0x000EE3;
constexpr uint24_t fxdeflect = 0x001245;
constexpr uint24_t fxtail_spin = 0x001367;
constexpr uint24_t fxtailspin = 0x001A29;
constexpr uint24_t fxparry = 0x003FAB;
constexpr uint24_t fxmonster = 0x0040CD;
constexpr uint24_t fxchip = 0x0052CF;
constexpr uint24_t fxpole = 0x005331;
constexpr uint24_t mh_map_tent = 0x0057E3;
constexpr uint24_t fxguard = 0x005A25;
constexpr uint24_t fxmonster_sweep = 0x005BD7;
constexpr uint24_t fxwhirlring = 0x007B59;
constexpr uint24_t fxspark = 0x00E75B;
constexpr uint24_t fxmonster_lunge = 0x00E78D;
constexpr uint24_t fxball = 0x01070F;
constexpr uint24_t fxchickenatk = 0x01073B;
constexpr uint24_t fxmonster_heavy = 0x01103D;
constexpr uint24_t fxbullatk = 0x012FBF;
constexpr uint24_t fxhooves_bull = 0x0138C1;
constexpr uint24_t fxtrail = 0x013C83;
constexpr uint24_t fxwhirl = 0x013CB5;
constexpr uint24_t fxhead_chicken = 0x013D77;
constexpr uint24_t fxplayer = 0x013E81;
constexpr uint24_t fxripspecial = 0x014003;
constexpr uint24_t fxtail_heavy = 0x0141B5;
constexpr uint24_t fxhead_bull = 0x014637;
constexpr uint24_t fxpole_crack = 0x014879;
constexpr uint24_t fxlegs_chicken = 0x01595B;
constexpr uint24_t fxpole_break = 0x015BE5;
constexpr uint24_t fxreload = 0x016CC7;
constexpr uint24_t fxscatter = 0x016D05;
constexpr uint24_t fxpole_sever = 0x016D1F;
constexpr uint24_t fxerase = 0x017E01;
constexpr uint24_t fxhud = 0x017E33;
constexpr uint24_t fxslash = 0x018075;
constexpr uint24_t fxfontg = 0x018F77;
constexpr uint24_t fxfontw = 0x019B79;
constexpr uint24_t mh_menu_wsel = 0x01A77B;
constexpr uint24_t mh_menu_msel = 0x01A9BD;
constexpr uint24_t mh_menu_bg = 0x01B5BF;
constexpr uint24_t mh_head_bandana = 0x01CDC1;
constexpr uint24_t mh_weapon_sword = 0x01D3C3;
constexpr uint24_t mh_head_helm = 0x021BC5;
constexpr uint24_t mh_player_base = 0x0221C7;
constexpr uint24_t mh_body_base = 0x0227C9;
constexpr uint24_t mh_shadow_base = 0x0233CB;
constexpr uint24_t mh_weapon_gun = 0x02348D;
constexpr uint24_t mh_head_base = 0x027C8F;
constexpr uint24_t mh_weapon_flail = 0x028291;
constexpr uint24_t mh_map_area = 0x02CA93;
constexpr uint24_t mh_map_camp = 0x030993;
constexpr uint24_t mh_map_pole_room = 0x031413;
